/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; ALTER SYSTEM SET DB_16K_CACHE_SIZE=4M SCOPE=BOTH;

CREATE USER MOVILES
  IDENTIFIED BY MOVILES
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
GRANT RESOURCE TO MOVILES;
GRANT CONNECT TO MOVILES;
ALTER USER MOVILES DEFAULT ROLE ALL;
  GRANT CREATE VIEW TO MOVILES;
GRANT UNLIMITED TABLESPACE TO MOVILES;
  GRANT CREATE ANY TABLE TO MOVILES WITH ADMIN OPTION;
  GRANT CREATE SESSION TO MOVILES;