/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

ALTER TABLE MOVILES.USUARIO DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.MATRICULA DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.GRUPO DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.ALUMNO DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.CICLO DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.PROFESOR DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.CARRERA_CURSO DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.CURSO DROP PRIMARY KEY CASCADE;
ALTER TABLE MOVILES.CARRERA DROP PRIMARY KEY CASCADE;

DROP TABLE MOVILES.USUARIO CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.MATRICULA CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.GRUPO CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.ALUMNO CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.CICLO CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.PROFESOR CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.CARRERA_CURSO CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.CURSO CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVILES.CARRERA CASCADE CONSTRAINTS PURGE;

CREATE TABLE MOVILES.CARRERA (
    CODIGO_CARRERA VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    TITULO VARCHAR2(100) NOT NULL
);

CREATE TABLE MOVILES.CURSO (
    CODIGO_CURSO VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CREDITOS NUMBER NOT NULL,
    HORAS_SEMANALES NUMBER NOT NULL
);

CREATE TABLE MOVILES.CARRERA_CURSO (
    CARRERA_CURSO_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CODIGO_CARRERA VARCHAR2(20) NOT NULL,
    CODIGO_CURSO VARCHAR2(20) NOT NULL,
    ANIO NUMBER NOT NULL,
    CICLO NUMBER NOT NULL,
    ORDEN NUMBER NOT NULL,
    FOREIGN KEY (CODIGO_CARRERA) REFERENCES MOVILES.CARRERA(CODIGO_CARRERA),
    FOREIGN KEY (CODIGO_CURSO) REFERENCES MOVILES.CURSO(CODIGO_CURSO)
);

CREATE TABLE MOVILES.PROFESOR (
    CEDULA VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(100) NOT NULL
);

CREATE TABLE MOVILES.ALUMNO (
    CEDULA VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    CODIGO_CARRERA VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CODIGO_CARRERA) REFERENCES MOVILES.CARRERA(CODIGO_CARRERA)
);

CREATE TABLE MOVILES.CICLO (
    CICLO_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ANIO NUMBER NOT NULL,
    NUMERO NUMBER NOT NULL CHECK (NUMERO IN (1, 2)),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ACTIVO NUMBER(1) DEFAULT 0 CHECK (ACTIVO IN (0, 1))
);

CREATE TABLE MOVILES.GRUPO (
    GRUPO_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CICLO_ID NUMBER NOT NULL,
    CODIGO_CURSO VARCHAR2(20) NOT NULL,
    NUMERO_GRUPO NUMBER NOT NULL,
    HORARIO VARCHAR2(200) NOT NULL,
    CEDULA_PROFESOR VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CICLO_ID) REFERENCES MOVILES.CICLO(CICLO_ID),
    FOREIGN KEY (CODIGO_CURSO) REFERENCES MOVILES.CURSO(CODIGO_CURSO),
    FOREIGN KEY (CEDULA_PROFESOR) REFERENCES MOVILES.PROFESOR(CEDULA)
);

CREATE TABLE MOVILES.USUARIO (
    CEDULA VARCHAR2(20) PRIMARY KEY,
    CLAVE VARCHAR2(100) NOT NULL,
    TIPO_USUARIO VARCHAR2(20) NOT NULL CHECK (TIPO_USUARIO IN ('ADMINISTRADOR', 'MATRICULADOR', 'PROFESOR', 'ALUMNO'))
);

CREATE TABLE MOVILES.MATRICULA (
     MATRICULA_ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
     GRUPO_ID NUMBER NOT NULL,
     CEDULA_ALUMNO VARCHAR2(20) NOT NULL,
     NOTA NUMBER(5,2) DEFAULT NULL,
     FOREIGN KEY (GRUPO_ID) REFERENCES MOVILES.GRUPO(GRUPO_ID),
     FOREIGN KEY (CEDULA_ALUMNO) REFERENCES MOVILES.ALUMNO(CEDULA)
);