/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

-- ----------------- CRUD para Usuario -----------------

CREATE OR REPLACE PROCEDURE MOVILES.INSERTAR_USUARIO(
    P_CEDULA IN VARCHAR2,
    P_CLAVE IN VARCHAR2,
    P_TIPO_USUARIO IN VARCHAR2
) AS
BEGIN
    INSERT INTO MOVILES.USUARIO (CEDULA, CLAVE, TIPO_USUARIO) VALUES (P_CEDULA, P_CLAVE, P_TIPO_USUARIO);
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_USUARIOS RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.USUARIO;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ACTUALIZAR_USUARIO(
    P_CEDULA IN VARCHAR2,
    P_CLAVE IN VARCHAR2,
    P_TIPO_USUARIO IN VARCHAR2
) AS
BEGIN
    UPDATE MOVILES.USUARIO SET CLAVE = P_CLAVE, TIPO_USUARIO = P_TIPO_USUARIO WHERE CEDULA = P_CEDULA;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ELIMINAR_USUARIO(
    P_CEDULA IN VARCHAR2
) AS
BEGIN
    DELETE FROM MOVILES.USUARIO WHERE CEDULA = P_CEDULA;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_USUARIO_POR_CEDULA(
    P_CEDULA IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.USUARIO WHERE CEDULA = P_CEDULA;
    RETURN RESULT_CURSOR;
END;
/


CREATE OR REPLACE PROCEDURE MOVILES.LOGIN_USUARIO(
    p_cedula IN VARCHAR2,
    p_clave IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT cedula, clave, tipo_usuario
        FROM MOVILES.USUARIO
        WHERE cedula = p_cedula
          AND clave = p_clave;
END;
/
