/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/


-- ----------------- Matrícula -----------------

CREATE OR REPLACE PROCEDURE MOVILES.REGISTRAR_MATRICULA(
    P_GRUPO_ID IN NUMBER,
    P_CEDULA_ALUMNO IN VARCHAR2
) AS
BEGIN
    INSERT INTO MOVILES.MATRICULA (GRUPO_ID, CEDULA_ALUMNO) VALUES (P_GRUPO_ID, P_CEDULA_ALUMNO);
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ELIMINAR_MATRICULA(
    P_GRUPO_ID IN NUMBER,
    P_CEDULA_ALUMNO IN VARCHAR2
) AS
BEGIN
    DELETE FROM MOVILES.MATRICULA WHERE GRUPO_ID = P_GRUPO_ID AND CEDULA_ALUMNO = P_CEDULA_ALUMNO;
END;
/

-- ----------------- Registro de Notas -----------------

CREATE OR REPLACE PROCEDURE MOVILES.REGISTRAR_NOTA(
    P_GRUPO_ID IN NUMBER,
    P_ALUMNO_ID IN VARCHAR2,
    P_NOTA IN NUMBER
) AS
BEGIN
    INSERT INTO MOVILES.MATRICULA (GRUPO_ID, CEDULA_ALUMNO, NOTA) VALUES (P_GRUPO_ID, P_ALUMNO_ID, P_NOTA);
END;
/

-- ----------------- Historial Académico -----------------

CREATE OR REPLACE FUNCTION MOVILES.CONSULTAR_HISTORIAL(
    P_ALUMNO_ID IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.MATRICULA WHERE CEDULA_ALUMNO = P_ALUMNO_ID;
    RETURN RESULT_CURSOR;
END;
/