/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

-- ----------------- CRUD para Carrera -----------------

CREATE OR REPLACE PROCEDURE MOVILES.INSERTAR_CARRERA(
    P_CODIGO IN VARCHAR2,
    P_NOMBRE IN VARCHAR2,
    P_TITULO IN VARCHAR2
) AS
BEGIN
    INSERT INTO MOVILES.CARRERA (CODIGO_CARRERA, NOMBRE, TITULO) VALUES (P_CODIGO, P_NOMBRE, P_TITULO);
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CARRERAS RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CARRERA;
    RETURN RESULT_CURSOR;
END;

CREATE OR REPLACE PROCEDURE MOVILES.ACTUALIZAR_CARRERA(
    P_CODIGO IN VARCHAR2,
    P_NOMBRE IN VARCHAR2,
    P_TITULO IN VARCHAR2
) AS
BEGIN
    UPDATE MOVILES.CARRERA SET NOMBRE = P_NOMBRE, TITULO = P_TITULO WHERE CODIGO_CARRERA = P_CODIGO;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ELIMINAR_CARRERA(
    P_CODIGO IN VARCHAR2
) AS
BEGIN
    DELETE FROM MOVILES.CARRERA WHERE CODIGO_CARRERA = P_CODIGO;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CARRERA_POR_CODIGO(
    P_CODIGO IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CARRERA WHERE CODIGO_CARRERA = P_CODIGO;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CARRERA_POR_NOMBRE(
    P_NOMBRE IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CARRERA WHERE NOMBRE = P_NOMBRE;
    RETURN RESULT_CURSOR;
END;
/