/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

-- ----------------- CRUD para Curso -----------------

CREATE OR REPLACE PROCEDURE MOVILES.INSERTAR_CURSO(
    P_CODIGO IN VARCHAR2,
    P_NOMBRE IN VARCHAR2,
    P_CREDITOS IN NUMBER,
    P_HORAS_SEMANALES IN NUMBER
) AS
BEGIN
    INSERT INTO MOVILES.CURSO (CODIGO_CURSO, NOMBRE, CREDITOS, HORAS_SEMANALES) VALUES (P_CODIGO, P_NOMBRE, P_CREDITOS, P_HORAS_SEMANALES);
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CURSOS RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CURSO;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ACTUALIZAR_CURSO(
    P_CODIGO IN VARCHAR2,
    P_NOMBRE IN VARCHAR2,
    P_CREDITOS IN NUMBER,
    P_HORAS_SEMANALES IN NUMBER
) AS
BEGIN
    UPDATE MOVILES.CURSO SET NOMBRE = P_NOMBRE, CREDITOS = P_CREDITOS, HORAS_SEMANALES = P_HORAS_SEMANALES WHERE CODIGO_CURSO = P_CODIGO;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ELIMINAR_CURSO(
    P_CODIGO IN VARCHAR2
) AS
BEGIN
    DELETE FROM MOVILES.CURSO WHERE CODIGO_CURSO = P_CODIGO;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CURSO_POR_CODIGO(
    P_CODIGO IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CURSO WHERE CODIGO_CURSO = P_CODIGO;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CURSOS_POR_CARRERA(
    P_CODIGO_CARRERA IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CURSO WHERE CODIGO_CURSO IN (SELECT CODIGO_CURSO FROM MOVILES.CARRERA_CURSO WHERE CODIGO_CARRERA = P_CODIGO_CARRERA);
    RETURN RESULT_CURSOR;
END;

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CURSOS_POR_NOMBRE(
    P_NOMBRE IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CURSO WHERE NOMBRE = P_NOMBRE;
    RETURN RESULT_CURSOR;
END;