/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

-- ----------------- CRUD para Carrera_Curso -----------------

CREATE OR REPLACE PROCEDURE MOVILES.INSERTAR_CARRERA_CURSO(
    P_CODIGO_CARRERA IN VARCHAR2,
    P_CODIGO_CURSO IN VARCHAR2,
    P_ANIO IN NUMBER,
    P_CICLO IN NUMBER,
    P_ORDEN IN NUMBER
) AS
BEGIN
    INSERT INTO MOVILES.CARRERA_CURSO (CODIGO_CARRERA, CODIGO_CURSO, ANIO, CICLO, ORDEN) VALUES (P_CODIGO_CARRERA, P_CODIGO_CURSO, P_ANIO, P_CICLO, P_ORDEN);
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CARRERAS_CURSOS RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CARRERA_CURSO;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ACTUALIZAR_CARRERA_CURSO(
    P_CARRERA_CURSO_ID IN NUMBER,
    P_ANIO IN NUMBER,
    P_CICLO IN NUMBER,
    P_ORDEN IN NUMBER
) AS
BEGIN
    UPDATE MOVILES.CARRERA_CURSO SET ANIO = P_ANIO, CICLO = P_CICLO, ORDEN = P_ORDEN WHERE CARRERA_CURSO_ID = P_CARRERA_CURSO_ID;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ELIMINAR_CARRERA_CURSO(
    P_CARRERA_CURSO_ID IN NUMBER
) AS
BEGIN
    DELETE FROM MOVILES.CARRERA_CURSO WHERE CARRERA_CURSO_ID = P_CARRERA_CURSO_ID;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_CARRERA_CURSO_POR_ID(
    P_CARRERA_CURSO_ID IN NUMBER
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.CARRERA_CURSO WHERE CARRERA_CURSO_ID = P_CARRERA_CURSO_ID;
    RETURN RESULT_CURSOR;
END;
/