/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

-- ----------------- CRUD para Alumno -----------------

CREATE OR REPLACE PROCEDURE MOVILES.INSERTAR_ALUMNO(
    P_CEDULA IN VARCHAR2,
    P_NOMBRE IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_FECHA_NACIMIENTO IN DATE,
    P_CODIGO_CARRERA IN VARCHAR2
) AS
BEGIN
    INSERT INTO MOVILES.ALUMNO (CEDULA, NOMBRE, TELEFONO, EMAIL, FECHA_NACIMIENTO, CODIGO_CARRERA) VALUES (P_CEDULA, P_NOMBRE, P_TELEFONO, P_EMAIL, P_FECHA_NACIMIENTO, P_CODIGO_CARRERA);
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_ALUMNOS RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.ALUMNO;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ACTUALIZAR_ALUMNO(
    P_CEDULA IN VARCHAR2,
    P_NOMBRE IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_FECHA_NACIMIENTO IN DATE,
    P_CODIGO_CARRERA IN VARCHAR2
) AS
BEGIN
    UPDATE MOVILES.ALUMNO SET NOMBRE = P_NOMBRE, TELEFONO = P_TELEFONO, EMAIL = P_EMAIL, FECHA_NACIMIENTO = P_FECHA_NACIMIENTO, CODIGO_CARRERA = P_CODIGO_CARRERA WHERE CEDULA = P_CEDULA;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ELIMINAR_ALUMNO(
    P_CEDULA IN VARCHAR2
) AS
BEGIN
    DELETE FROM MOVILES.ALUMNO WHERE CEDULA = P_CEDULA;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_ALUMNO_POR_CEDULA(
    P_CEDULA IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.ALUMNO WHERE CEDULA = P_CEDULA;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_ALUMNO_POR_NOMBRE(
    P_NOMBRE IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.ALUMNO WHERE NOMBRE = P_NOMBRE;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_ALUMNOS_POR_CARRERA(
    P_CODIGO_CARRERA IN VARCHAR2
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.ALUMNO WHERE CODIGO_CARRERA = P_CODIGO_CARRERA;
    RETURN RESULT_CURSOR;
END;
/