/*
    * @author: Derek Rojas Mendoza
    * @author: Joseph León Cabezas
*/

-- ----------------- CRUD para Grupo -----------------

CREATE OR REPLACE PROCEDURE MOVILES.INSERTAR_GRUPO(
    P_CICLO_ID IN NUMBER,
    P_CODIGO_CURSO IN VARCHAR2,
    P_NUMERO_GRUPO IN NUMBER,
    P_HORARIO IN VARCHAR2,
    P_CEDULA_PROFESOR IN VARCHAR2
) AS
BEGIN
    INSERT INTO MOVILES.GRUPO (CICLO_ID, CODIGO_CURSO, NUMERO_GRUPO, HORARIO, CEDULA_PROFESOR) VALUES (P_CICLO_ID, P_CODIGO_CURSO, P_NUMERO_GRUPO, P_HORARIO, P_CEDULA_PROFESOR);
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_GRUPOS RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.GRUPO;
    RETURN RESULT_CURSOR;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ACTUALIZAR_GRUPO(
    P_GRUPO_ID IN NUMBER,
    P_HORARIO IN VARCHAR2,
    P_CEDULA_PROFESOR IN VARCHAR2
) AS
BEGIN
    UPDATE MOVILES.GRUPO SET HORARIO = P_HORARIO, CEDULA_PROFESOR = P_CEDULA_PROFESOR WHERE GRUPO_ID = P_GRUPO_ID;
END;
/

CREATE OR REPLACE PROCEDURE MOVILES.ELIMINAR_GRUPO(
    P_GRUPO_ID IN NUMBER
) AS
BEGIN
    DELETE FROM MOVILES.GRUPO WHERE GRUPO_ID = P_GRUPO_ID;
END;
/

CREATE OR REPLACE FUNCTION MOVILES.OBTENER_GRUPO_POR_ID(
    P_GRUPO_ID IN NUMBER
) RETURN SYS_REFCURSOR AS
    RESULT_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN RESULT_CURSOR FOR SELECT * FROM MOVILES.GRUPO WHERE GRUPO_ID = P_GRUPO_ID;
    RETURN RESULT_CURSOR;
END;
/